# Generated by Django 3.1.6 on 2021-02-19 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LabProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('objective', models.TextField()),
                ('task', models.TextField(default='')),
                ('input_content', models.TextField()),
                ('output_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FileField(upload_to='assignmentSubmissions/')),
                ('approved', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('teachers_remarks', models.TextField(default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.assignments')),
            ],
        ),
        migrations.AddField(
            model_name='assignments',
            name='problems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labproblems'),
        ),
    ]
