# Generated by Django 3.1.6 on 2021-02-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='problems',
        ),
        migrations.AddField(
            model_name='assignments',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='assignments',
            name='input_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='assignments',
            name='objective',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='assignments',
            name='output_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='assignments',
            name='task',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='assignments',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
