# Generated by Django 3.1.6 on 2021-02-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20210219_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
