# Generated by Django 3.1.6 on 2021-02-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_assignments_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmissions',
            name='teachers_remarks',
        ),
        migrations.AddField(
            model_name='assignments',
            name='teachers_remarks',
            field=models.TextField(default=''),
        ),
    ]
