# Generated by Django 3.1.6 on 2021-02-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('input_content', models.TextField()),
                ('output_content', models.TextField()),
            ],
        ),
    ]
