# Generated by Django 3.1.6 on 2021-02-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='content',
            new_name='objective',
        ),
        migrations.AddField(
            model_name='problems',
            name='task',
            field=models.TextField(default=''),
        ),
    ]
