# Generated by Django 3.1.6 on 2021-02-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20210216_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='head',
            field=models.CharField(default='Lab One', max_length=30),
        ),
    ]
