# Generated by Django 3.1.6 on 2021-02-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_problems_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
