# Generated by Django 3.1.6 on 2021-02-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='title',
            field=models.TextField(default='Code', max_length=100),
        ),
    ]
