# Generated by Django 3.1.6 on 2021-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_auto_20210217_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='problem',
            field=models.CharField(default='', max_length=100),
        ),
    ]
