# Generated by Django 3.1.6 on 2021-02-18 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice', '0007_auto_20210217_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.problems'),
        ),
    ]
