# Generated by Django 3.1.6 on 2021-02-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_auto_20210218_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='title',
        ),
    ]
