# Generated by Django 3.1.6 on 2021-02-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_remove_submissions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
